name: Start SSH via tmate
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: P3TERX/ssh2actions@v1.0.0
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
